version: '3.8'

services:

  # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
  # https://github.com/MariaDB/mariadb-docker/blob/master/examples/compose-replication.yml
  database:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    ports:
      - 3306:3306
    volumes:
      - ./storage/datadir:/var/lib/mysql
    command: [
      '--wait_timeout=3600',
      '--log-warnings=9',
    ]
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12204"
        tag: "docker_mariadb"